[book]
title = "ME360 Portfolio"
authors = ["Joel Gutierrez Wirtz"]
language = "en"
src = "src" # Explicitly tell it where your markdown files are

[output.html]
git-repository-url = "https://github.com/testguy20031/ME360Portfolio"
site-url = "/ME360Portfolio/"
mathjax-support = true
